# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check the build file for more details.
# For more details on how to configure your build environment visit
# http://www.gradle.org/configure-build-environment

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does not include resources from the
# dependencies, thereby reducing the size of the R class for that library
android.nonTransitiveRClass=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Enable Gradle build cache
org.gradle.caching=true

# Enable parallel build
org.gradle.parallel=true

# JVM memory
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m

# Compose
android.enableCompose=true
